### ISSUE TITLE
Non assigned boundary conditions should be "null" instead of "0" 

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#428] opened 2018-07-11 08:45 UTC
This gives problems with plasticity and other problematics

**Comment by loumalouomega** [comment] 2018-07-11 10:32
Maybe the solution would be differentiate between not set ->null, set but not constrained and set but constrained

**Comment by jginternational** [comment] 2018-07-11 10:43
Be carefull... 
https://www.youtube.com/watch?v=f7uD6j3Oe0w

This was the origin of the ancient Solid-Structural war

**Comment by jginternational** [comment] 2018-07-11 11:00
Let's wait to @RiccardoRossi 's and @pooyan-dadvand opinion

**Comment by philbucher** [comment] 2019-04-25 08:24
+1 for the proposal of @loumalouomega 
It seems like at least for structural its not a war but rather a consenses :+1: 

we are having problems with this over and over again, the latest was @KlausBSautter

**Comment by pooyan-dadvand** [comment] 2019-04-25 08:50
I have added this to @KratosMultiphysics/technical-committee todo

**Comment by AlejandroCornejo** [comment] 2019-04-25 09:50
+1 to the proposal! this issue always gives problems (at least for me and some students that use the CL)
Thank you @loumalouomega

**Comment by rubenzorrilla** [comment] 2019-04-26 08:16
+1. The proposal also makes sense to me. 

But how can this be translated to the GiD GUI? @jginternational would it be possible to add another checkbox as the X, Y and Z constraint that says X, Y and Z do nothing (or something similar)

**Comment by jginternational** [comment] 2019-04-26 10:22
@rubenzorrilla 
That's already implemented for 3-component (XYZ) parameters. You can use the Enable field in the parameter.
for example:
Enable_X = true
Value_X = 0.0
Enable_Y = false
Enable_Z = true
ByFunction_Z = true
Function_Z = 2*t

(I'm out of the office now so I can't attach a screenshot)

**Comment by rubenzorrilla** [comment] 2019-04-26 10:46
But eventually this would have to be selected by the user such that if not enabled it the project parameters writing sets null. Am I wrong?

**Comment by RiccardoRossi** [comment] 2019-04-26 12:46
I am a little lost :-(

is the documentation here wrong?

https://github.com/KratosMultiphysics/Kratos/wiki/How-to-use-Processes-In-the-application-of-BCs

**Comment by RiccardoRossi** [comment] 2019-05-09 11:11
ping!

**Comment by pooyan-dadvand** [comment] 2019-05-21 11:15
@KratosMultiphysics/technical-committee would like to know the opinion of @KratosMultiphysics/interface-committee about it as it directly changes the current input.

**Comment by pooyan-dadvand** [comment] 2019-05-30 11:15
Any comment from @KratosMultiphysics/interface-committee?

**Comment by antonialarese** [comment] 2019-05-31 07:07
@pooyan-dadvand sorry for the silence. I would need a brief summary since from the discussion is not fully clear what you are discussing exactly. As @RiccardoRossi , I am a bit lost.

As far as I know now there is the CONSTRAINED/NOT CONSTRAINED "flag" for each variable (and relative components, right? Is that the thing that gives problems? Or  are you now asking to set  the VALUE associated to the not constrained variable to "null"? Is that what you are asking?

**Comment by pooyan-dadvand** [comment] 2019-05-31 08:10
The constrained flag is for imposing the dirichlet condition: If constrained we fix the dof. But if is not the value applied without fixing the dof. The problem is that this value applies in each time step now. 

There is another flag `ENABLE` which says if any value assigned to the node which is useful for vector component when we want to apply a value to component x but not to the rest. However this flag is not passed to Kratos and the question of this issue is if we pass it by setting the value to null. 

@rubenzorrilla am I right? Would you please correct/complete my description?

**Comment by rubenzorrilla** [comment] 2019-05-31 08:42
@pooyan-dadvand yes you're right. In any case I'll try to further clarify this. 

Imagine that the user wants to set, component by component, the values of one vector variable. According to my understanding, for each component there are 3 options:
1) Do nothing
2) Set but let it free
3) Set and fix
Note that due to the manner we implemented the processes in the analysis stage, any of these operations will be done at the beginning of all time steps inside the interval in which the process lives (e.g. if the process interval is `"interval": [0.0, "End"] it is applied at each time step).

In for Kratos, we have a clear definition for 1), 2) and 3)
1) Do nothing --> set the component value to **"null"**. This does nothing (keep the value in buffer)
2) Set but let it free --> sets the component value to a double
3) Set and fix --> sets the component value to a double and fixes it. Note that the "constrained" value is `True` in this case

So far, there is no problem in the Kratos side. The problem arises in the GiD GUI, since the concept **null** doesn't exist. Thus, "do nothing" (option 1) turns to be (option 2) in all the cases since the value is set to zero instead of null. According to my understanding, what we are doing in here is to set a wrong prediction, which as @loumalouomega pointed when the issue arose, this might give problems in some applications, and aside of this, we are silently changing the behaviour that the user might expect.

I hope this clarifies the issue.

**Comment by RiccardoRossi** [comment] 2019-05-31 08:49
but, can't we have a "do nothing" option in gid, which actually writes "null"?

**Comment by rubenzorrilla** [comment] 2019-05-31 09:22
> but, can't we have a "do nothing" option in gid, which actually writes "null"?

I briefly discussed this with @jginternational and he has some ideas to do this.

**Comment by pooyan-dadvand** [comment] 2019-05-31 09:50
But in GiD we have the Enable_X = true, we may import that one instead of null in value. What would be the advantage/disadvantage of using null in value respect to using another parameter?

**Comment by RiccardoRossi** [comment] 2019-05-31 09:51
null is a keyword in json ...

**Comment by RiccardoRossi** [comment] 2019-05-31 09:52
also changing the interface would break existing code that works correctly

**Comment by rubenzorrilla** [comment] 2019-05-31 09:52
And all of our processes assume that "null is provided in "values" array not in an "enabled" array

**Comment by pooyan-dadvand** [comment] 2019-05-31 09:55
I see. Thanks!

**Comment by jginternational** [comment] 2019-06-04 10:00
I'm working on it and I'll bring a solution this week

@KratosMultiphysics/interface-committee

**Comment by RiccardoRossi** [comment] 2019-06-18 14:35
ping @KratosMultiphysics/interface-committee

**Comment by rubenzorrilla** [comment] 2019-07-10 11:19
ping @KratosMultiphysics/interface-committee

**Comment by antonialarese** [comment] 2019-07-10 13:41
@rubenzorrilla: we had a brief mail discussion  a couple of weeks ago and @jginternational asked for more time since he was working on a possible solution.
@jginternational: any news?

**Comment by jginternational** [comment] 2019-07-10 14:49
I'm writing the long answer, which contains more questions

**Comment by jginternational** [comment] 2019-07-10 16:50
Let's see your impressions by checking some situations in the current GUI, and the equivalent in the new proposal:
## Fixin all 
### Old gui
![image](https://user-images.githubusercontent.com/5918085/60980991-d09c2900-a335-11e9-9347-da9153156493.png)
You can see that there is a lot of information in the screen. This will generate the following json:
```
{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_Displacement_Auto1",
                "variable_name"   : "DISPLACEMENT",
                "constrained"     : [true,true,true],
                "value"           : [0.0,0.0,0.0],
                "interval"        : [0.0,"End"]
            }
}
```
### New
![image](https://user-images.githubusercontent.com/5918085/60987125-4063e100-a341-11e9-8976-d00700bb4f8f.png)
It's a more compact solution (better for small screens) and simplifies the data input. Generates the following json:
```
{
        "constraints_process_list" : [{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_Displacement_Auto1",
                "variable_name"   : "DISPLACEMENT",
                "constrained"     : [true,true,true],
                "value"           : [0.0,0.0,0.0],
                "interval"        : [0.0,"End"]
            }
 }
```
As you can see, it's the same json as the old one

## Fix only X
### Old gui
![image](https://user-images.githubusercontent.com/5918085/60986351-92a40280-a33f-11e9-8e51-c99885347914.png)
This case generates the following json:
```
{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_Displacement_Auto2",
                "variable_name"   : "DISPLACEMENT",
                "constrained"     : [false,false,true],
                "value"           : [0.0,0.0,"(y/2)*t"],
                "interval"        : [0.0,"End"]
            }
}
```
And the problem here is that the X and Y axis are not set to null, and the json is still valid.

### New
![image](https://user-images.githubusercontent.com/5918085/60987576-2c6caf00-a342-11e9-8994-47e7d86a3ac2.png)
Again, you can see a compact design, that generates the following json:
```
{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_Displacement_Auto2",
                "variable_name"   : "DISPLACEMENT",
                "constrained"     : [false,false,true],
                "value"           : [null,null,"(y/2)*t"],
                "interval"        : [0.0,"End"]
            }
}
```
This way, X and Y displacement will be **NULL instead of 0.0**. If I want to set those components to 0.0, I'll need to create another assignation to the same group and select XY as Axis.
![image](https://user-images.githubusercontent.com/5918085/60988008-114e6f00-a343-11e9-9c74-95c9de0f84a1.png)


If you agree, I'll work on this solution and will be applied to all conditions that use the `assign_vector_variable_process` process

**Comment by rubenzorrilla** [comment] 2019-07-16 15:58
From the description above I understand that it is possible to impose more than one direction at the same time only if the value is the same for all the constrained (or initialized) directions.

What I don't like so much is that it is needed to set multiple constraints if the value between the directions to be set is different. The point is that there is no unique manner...

**Comment by rubenzorrilla** [comment] 2019-10-01 15:10
Dear all,

#624 has been finally merged. The changes in the GUI solve the `0` vs. `null` issue. Please note that the changes imply that the old cases won't be compatible anymore since the transform tool can't handle the changes in the vectorial displacements.

**Closed by rubenzorrilla** 2019-10-01 15:10 UTC
Labels: decision needed, enhancement, help wanted
