### ISSUE TITLE
Updating StructuralMechanics Solvers

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/GiDInterface#159] opened 2017-10-17 14:51 UTC
Hi @jginternational 
Here I list the changes that should be made to the problemtype for PR [#850](https://github.com/KratosMultiphysics/Kratos/pull/850)
All the changes are under `Model Information`. These are the settings that should be there from now on, for static and dynamic analysis:

Solver Type : Static (formerly: Solution Type)
Solution Strategy: No longer needed
Scheme: Also not needed
Analysis type: leave as is

Solver Type : Dynamic (formerly: Solution Type)
Time Integration Method : Implicit (=> other options will be added in the future)
Scheme: Leave as is
Analysis Type: Same as for Static, i.e. Linear or Non-Linear

These settings also have to be written to the ProjectParameters, under `solver_settings`:
```
"solver_type"     : "static" / "dynamic"
"analysis_type"  : "linear" / "non_linear"
in case of Dynamic:
"time_integration_method" : "implicit"
"scheme_type" : "newmark" / "bossak"
```

Another minor change was done with the naming of the convergence criteria; they are all lower case with underscores, according to the [style Guide](https://github.com/KratosMultiphysics/Kratos/wiki/Style-Guide)
Thanks a lot!

**Comment by philbucher** [comment] 2017-10-24 06:45
@jginternational the changes are merged now, please feel free to apply the modifications to the ProblemType. Or show me where to do it, then I can try to do it myself.

**Comment by philbucher** [comment] 2017-10-24 07:35
Also we removed the old beam `SmallDisplacement...`, it is replaced by `CrLinearBeamElement3D2N` and `CrBeamElement3D2N`
Furthermore we added two more shell elements: a Quad `ShellThinElementCorotational3D4N` and a Triangle `ShellThickElementCorotational3D3N`

**Comment by philbucher** [comment] 2017-10-24 07:36
And there are now also trusses: `TrussLinearElement3D2N` and `TrussElement3D2N`

**Comment by rubenzorrilla** [comment] 2017-10-24 14:06
@philbucher I'm tackling the new structural solver inconsistencies.

**Comment by rubenzorrilla** [comment] 2017-10-24 14:56
@philbucher, @jginternational  and me (together with @loumalouomega ), think that its better to keep the old camel format to avoid breaking the interface as much as possible. Thus, @loumalouomega is doing a PR changing the structure solvers wrapper according to the next convention:

- "solver_type"     : "Static" / "Dynamic"
- "analysis_type"  : "Linear" / "NonLinear"
in case of Dynamic:
- "time_integration_method" : "Implicit"
- "scheme_type" : "Newmark" / "Bossak"

**Comment by philbucher** [comment] 2017-10-24 15:42
Thanks @rubenzorrilla !
Regarding the interface I do not agree though. The [Style Guide](https://github.com/KratosMultiphysics/Kratos/wiki/Style-Guide) is there for a reason and I really think this is a good point of applying it. 
The whole idea of the PR I did was to have it clean! 
Also the interface is already broken with the other (more drastic) changes and I have implemented clear error messages that tell the available options

**Comment by AndreasWinterstein** [comment] 2017-10-24 16:09
Hi @rubenzorrilla and @loumalouomega. If we are changing the interface anyway, I think it would make sense to stick to the Style Guide. This is the reason why we chose the format as it is now. Doing this would reduce confusion, when adding new solvers in the future. What do you think?

**Comment by rubenzorrilla** [comment] 2017-10-24 16:33
I agree, but what we have done is according to the [JSON file convention](https://github.com/KratosMultiphysics/Kratos/wiki/How-to-write-a-JSON-configuration-file) in here. In this example the field naming convention follows the style guide, the mismatch is in the variable content (maybe this is not so bad...).  Thus, we need to update it (this is probably another issue).

In any case, to change things as the residual criteria naming is simple, we can fit to your work. The point is in the "Dynamic/Static", "Implicit", etc... variables, since they are used for filtering purposes in the interface. This means that modifying them surely yield a lot of debugging work. Considering that we have only 8 days for preparing the release and that it is more or less stable right now, it is not a good idea to change these kind of filtering parameters.

Thus, we will try to respect as much as possible you naming proposal for the next release. Once the release version is packaged, we can work on the remaining mismatches.

**Comment by rubenzorrilla** [comment] 2017-10-24 16:38
By the way, do you want the "relaxation" scheme to appear in the interface?

**Comment by philbucher** [comment] 2017-10-24 18:12
Hi @rubenzorrilla 
I don't think the relaxation scheme is necessary in the interface
I didn't really get what you mean with "The point is in the "Dynamic/Static", "Implicit", etc... variables, since they are used for filtering purposes in the interface", but it seems like you have reasons why this should not be in the release, so I am / we are fine with it
Maybe you could explain that a bit more then we can take it into account after the release

**Comment by rubenzorrilla** [comment] 2017-10-25 09:28
Hi  @philbucher,

Maybe @jginternational can give a better explanation. But in a nutshell, the problem is that the "Dynamic/Static" variables are used to filter what is shown in the interface. Therefore, they appear in multiple internal methods of the interface (for instance to make the "time_scheme" field appear when you select "dynamic"). As we have discussed, this is a potential source of errors that we want to avoid before the release.

Of course we can work on it after the release date. Hope this explanation clarifies your doubts.

**Comment by rubenzorrilla** [comment] 2017-10-25 12:21
We've opened two new issues for the new shell and truss elements addition. Hence, we can close this one.

**Closed by rubenzorrilla** 2017-10-25 12:21 UTC
